export const apiEndpoints = {
  welcome: "/",
  home: "/",
  signIn: "/user/signin",
  signUp: "/user/signup",
  // FARM
  farm: "/farm",
  farmDetails: "/farm/:farmId",
  createFarm: "/farm",
  deleteFarm: "/farm/:farmId",
  updateFarm: "/farm/:farmId",
  // FIELD
  field: "/field",
  fieldDetails: "/field/:fieldId",
  fieldsByFarm: "/field/by-farm/:farmId",
  createField: "/field",
  deleteField: "/field/:fieldId",
  updateField: "/field/:fieldId",
  // MACHINE
  machine: "/machine",
  machineDetails: "/machine/:machineId",
  machinesByFarm: "/machine/by-farm/:farmId",
  machinesByField: "/machine/by-field/:fieldId",
  machinesByGrowingPeriod: "/machine/by-growing-period/:growingPeriodId",
  createMachine: "/machine",
  deleteMachine: "/machine/:machineId",
  updateMachine: "/machine/:machineId",
  transferMachine: "/machine/transfer/:id/:fromFarmId/:toFarmId",

  // PROCESSING
  processing: "/processing",
  createProcessing: "/processing",
  deleteProcessing: "/processing/:processingId",
  processingsByGrowingPeriod: "/processing/by-growing-period/:growingPeriodId",
  // PROCESSING-TYPE
  processingType: "/processing-type",
  createProcessingType: "/processing-type",
  deleteProcessingType: "/processing-type/:processingTypeId",
  // CROP
  crop: "/crop",
  cropDetails: "/crop/:cropId",
  createCrop: "/crop",
  deleteCrop: "/crop/:cropId",
  // SOIL
  soil: "/soil",
  soilDetails: "/soil/:soilId",
  createSoil: "/soil",
  deleteSoil: "/soil/:soilId",
  // GROWING-PERIOD
  growingPeriod: "/growing-period",
  growingPeriodDetails: "/growing-period/:growingPeriodId",
  growingPeriodsByField: "/growing-period/by-field/:fieldId",
  createGrowingPeriod: "/growing-period",
  deleteGrowingPeriod: "/growing-period/:growingPeriodId",
};
