// TODO
export const routes = {
  welcome: "/",
  home: "/home",
  farm: "/farm",
  farmDetails: "/farm/:farmId",
  createFarm: "/farm-create",
  field: "/field",
  fieldDetails: "/field/:fieldId",
  createField: "/field-create",
  machine: "/machine",
  machineDetails: "/machine/:machineId",
  createMachine: "/machine-create",
  processing: "/processing",
  createProcessing: "/processing-create",
  processingType: "/processing-type",
  createProcessingType: "/processing-type-create",
  crop: "/crop",
  createCrop: "/crop-create",
  soil: "/soil",
  createSoil: "/soil-create",
  signIn: "/user/signin",
  notFound: "/*",
};
